---
title: "initial"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(jsonlite)

#CEX.io
# https://cex.io/api/ticker/BTC/USD

CEX_all <- read_json("https://cex.io/api/ticker/BTC/USD")
CEX_BTClast <- as.numeric(CEX_all$last, type = "double")

# Luno
# https://api.mybitx.com/api/1/ticker?pair=XBTZAR

Luno_all <- read_json("https://api.mybitx.com/api/1/ticker?pair=XBTZAR")
Luno_BTClast <- as.numeric(Luno_all$last_trade, type = "double")

# Fixer currency
# http://api.fixer.io/latest?base=USD

# Currency layer
# http://apilayer.net/api/live?access_key=fb4098900a0d9b09598c1895b7cf65bf&currencies=ZAR&format=1

CL_all <- read_json("http://apilayer.net/api/live?access_key=fb4098900a0d9b09598c1895b7cf65bf&currencies=ZAR&format=1")
CL_ZArlast <- as.numeric(CL_all$quotes$USDZAR, type = "double")

# Calculate premium
Luno_premium <- (Luno_BTClast / CL_ZArlast) / CEX_BTClast
Luno_premium

# if (Luno_premium >= 1.08){
#   library(mailR)
#   text_to_send <- paste0("Arbitrage opp - premium is: ", round(Luno_premium, 4))
#   send.mail(from = "blakec.mailr@gmail.com",
#           to = c("blake.rsa@gmail.com"),
#           replyTo = c("blake.rsa@gmail.com"),
#           subject = "BTC Arbitrage opportuntity",
#           body = text_to_send,
#           smtp = list(host.name = "smtp.gmail.com", port = 465, user.name = "blakec.mailr", passwd = "*@xPx95RV&p30CLZ", ssl = TRUE),
#           authenticate = TRUE,
#           send = TRUE)
# } else {
#   print(paste0("No opportunity, premium is only: ", round(Luno_premium, 4)))
# }




```

```{r}

intermediate_check <- readRDS("tracking_df.rds")

```


/Users/blakecuningham/Documents/DataScienceData/BitcoinArbitrage/BitcoinArbitrageNotification/170918_ArbitrageEmail.R